name: workoutproject
description: "A Fitness Tracker application built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^6.5.7
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.2.1
  fl_chart: ^0.61.0
  intl: ^0.17.0  # Downgraded to be compatible with charts_flutter
  flutter_svg: ^2.0.7

  timezone: ^0.10.0  # For TZDateTime support
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
dependency_overrides:
  intl: ^0.17.0
